"""delete barcode and price in transaction model

Revision ID: 1127844adb29
Revises: 8c386ae53d2f
Create Date: 2026-09-25 23:10:53.565445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1127844adb29'
down_revision: Union[str, Sequence[str], None] = '8c386ae53d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'barcode')
    op.drop_column('transaction', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
