"""add need_supplier to transaction Type

Revision ID: 18afd3a01b15
Revises: eac85f4abbe1
Create Date: 2026-09-25 23:04:50.662409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18afd3a01b15'
down_revision: Union[str, Sequence[str], None] = 'eac85f4abbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_type', sa.Column('need_supplier', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_type', 'need_supplier')
    # ### end Alembic commands ###
