"""adding productSupplier and supplier table

Revision ID: 19730ba6ab2b
Revises: 49be41b39a6b
Create Date: 2026-09-26 14:53:01.657094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19730ba6ab2b'
down_revision: Union[str, Sequence[str], None] = '49be41b39a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('transaction', 'supplier')
    op.drop_column('transaction', 'buy_price')
    op.add_column('transaction_item', sa.Column('product_supplier_id', sa.Integer(), nullable=True))
    op.add_column('transaction_item', sa.Column('unit_price', sa.Integer(), nullable=False))
    op.add_column('transaction_item', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transaction_item', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('transaction_item_transaction_type_id_fkey'), 'transaction_item', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_item', 'product_supplier', ['product_supplier_id'], ['id'])
    op.drop_column('transaction_item', 'transaction_type_id')
    op.drop_column('transaction_item', 'subtotal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_item', sa.Column('subtotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transaction_item', sa.Column('transaction_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transaction_item', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_item_transaction_type_id_fkey'), 'transaction_item', 'transaction_type', ['transaction_type_id'], ['id'])
    op.drop_column('transaction_item', 'updated_at')
    op.drop_column('transaction_item', 'created_at')
    op.drop_column('transaction_item', 'unit_price')
    op.drop_column('transaction_item', 'product_supplier_id')
    op.add_column('transaction', sa.Column('buy_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('supplier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('product_supplier')
    op.drop_table('supplier')
    # ### end Alembic commands ###
