"""change supplier and buy price to nullable=True

Revision ID: 49be41b39a6b
Revises: 1127844adb29
Create Date: 2026-09-25 23:41:14.371434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49be41b39a6b'
down_revision: Union[str, Sequence[str], None] = '1127844adb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'supplier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transaction', 'buy_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'buy_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction', 'supplier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
