"""add description to Transaction Type

Revision ID: 4a0f43bce8a9
Revises: df0bbc8d1900
Create Date: 2026-09-25 16:50:19.090909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0f43bce8a9'
down_revision: Union[str, Sequence[str], None] = 'df0bbc8d1900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_type', sa.Column('description', sa.String(length=50), nullable=False))
    op.drop_column('transaction_type', 'detail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_type', sa.Column('detail', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('transaction_type', 'description')
    # ### end Alembic commands ###
