"""revision id and time field

Revision ID: 73d3d7adc10e
Revises: 69b823394856
Create Date: 2026-09-23 15:26:28.038223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d3d7adc10e'
down_revision: Union[str, Sequence[str], None] = '69b823394856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('category', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('category', 'descriptions')
    op.drop_column('category', 'update_at')
    op.drop_column('category', 'create_at')
    op.add_column('product', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('product', 'create_at')
    op.drop_column('product', 'buy_price')
    op.drop_column('product', 'update_at')
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transaction', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('transaction', 'create_at')
    op.drop_column('transaction', 'update_at')
    op.add_column('transaction_type', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transaction_type', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('transaction_type', 'create_at')
    op.drop_column('transaction_type', 'update_at')
    op.add_column('unit', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('unit', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('unit', 'create_at')
    op.drop_column('unit', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('unit', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('unit', 'updated_at')
    op.drop_column('unit', 'created_at')
    op.add_column('transaction_type', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('transaction_type', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('transaction_type', 'updated_at')
    op.drop_column('transaction_type', 'created_at')
    op.add_column('transaction', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'updated_at')
    op.drop_column('transaction', 'created_at')
    op.add_column('product', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('buy_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.add_column('category', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('descriptions', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    op.drop_column('category', 'description')
    # ### end Alembic commands ###
