"""add description to unit

Revision ID: df0bbc8d1900
Revises: 73d3d7adc10e
Create Date: 2026-09-25 16:43:56.357422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0bbc8d1900'
down_revision: Union[str, Sequence[str], None] = '73d3d7adc10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('description', sa.String(length=255), nullable=False))
    op.drop_column('unit', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('descriptions', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('unit', 'description')
    # ### end Alembic commands ###
